server:
    address: 127.0.0.1
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/heleeos?useUnicode=true&characterEncoding=utf8
        username: blog
        password: blog123
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.heleeos.blog.dao.dto
    #configLocation: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mappers/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
